# Angela Script

label angela_1:
  anon "Hello, Phat Pies, home of the Thick and Meaty™. Can I take your order?"
  mc "Yes, this is my first time ordering. Would you say the Thick and Meaty is one of your more popular items?"
  anon "Yeah, that or the \"Rollin’ in Dough\"."
  mc "Is that a calzone?"
  anon "Sort of. It’s a whole pizza rolled inside phyllo-dough and then deep fried in butter."
  mc "Sounds... interesting... but no. No one likes calzones. They’re just pizza that’s harder to eat. I’ll take the \"Thick and Meaty\""
  anon "Alright, it’ll be \"hot and right on to ya in 30 minutes or less!\""
  anon "..."
  anon "That’s our delivery slogan. I have to say it. Please don’t hold it against me."
  anon "*click*"

  scene black
  with dissolve
  pause 2.0
  "*Knock, Knock, Kock*"
  mc " (Ah, sounds like my meal has arrived)"

  python:
    ang.name = "???"
  show bg frontdoor night
  pause 1.0
  show angela

  ang "[locPizza] Here’s your order."
  "She holds out the pizza box and looks away"
  mc "Hm... I called in this order over an hour ago. Don’t you have some kind of delivery guarantee?"
  ang "Look dude, talk is cheap and so is this pizza. You can call corporate and whine over your $10 if you want. I don’t care. For me, the only question is are you going to take this pizza or am I?"
  mc "(Quite a direct attitude. Hm. How best to handle this?)"
  mc "I guess you can just take the pizza, give me $10, and we’ll call it even."
  mc "(She suddenly jerks her head back to look at me. Anger and confusion written across her face.)"
  ang "What? That’s crazy. Why would I give you money? I’ll just leave."
  "(She starts to move away)"
  mc "Well. I already paid when I ordered. So if you take the pizza that would be theft in my book."
  ang "Fine. {i}Whatever{/i} just take the pizza then and call back in for a refund."
  "(She rolls her eyes and pushes the box towards me)"
  mc "Oh no. I’m not taking the box. I think you made it pretty clear that my complaints are unlikely to be taken seriously. I’ll never see that money again if I accept the delivery."
  "(She grits her teeth a bit; anger winning over confusion.)"
  ang "Just. Take. The. Pizza. … Dude."
  mc "So will you be giving me my $10?"
  "(she levels me with a menacing glare)"
  ang "Why would I pay you to take the pizza? That makes no sense. Fine. Just- I’ll take this back. Uhg."
  "(She goes to leave again.)"
  "(*Ring*)"
  "(I’ve pulled out my cell-phone and put it on speaker.)"
  "(*Ring*)"
  "(She looks back at me in disbelief.)"
  ang "What on earth are you—"
  locPizza "Hello, Phat Pies, home of the Thick and Meaty™. Can I take your order?"
  mc "Hi Yes. I have an employee of yours here who is refusing to deliver my pizza."
  ang "!?!-- That’s crazy I am not ref—"
  phone "Angela?! Oh my god… Are you harassing a customer so badly he had to call in while you are still there?!"
  phone "Sir. I can’t apologize for this enough. I assure you we will take care of everything. Of course we will refund your order, but please take it… on the house."
  ang "He wouldn’t take the pizza. He-"
  phone "Angela! Give the customer his order, and report back here. Immediately."
  "(She violently shoves the pizza in my direction.)"
  mc "Why thank you. I certainly appreciate a business with integrity."
  phone "Our pleasure sir. Please just call again anytime from this number and we will honor you with another free delivery."
  phone "Satisfied customers are our business after all! If there is anything else we can do for you let us know."
  mc "Of course. I’m sure I’ll be calling again soon."
  phone "*click*"
  ang "Are you serious right now? What was that?!?"
  mc "Angela, right? That’s a nice name. Look Angela. You did tell me to call didn’t you?"
  ang "You said-"
  "(I shrug)"
  mc "I never said I wouldn’t call… only that you implied it wouldn’t work."
  "(I grin at her wolfishly.)"
  mc "I guess you were wrong there. Maybe you just need to know how to work the system."
  ang "...."
  ang "Yeah. Well, I hope you enjoy your free pizza"
  mc "Two now."
  ang "Free Pizzas…"
  mc "Well, technically, one free pizza and a free future meal of my choice. :)"
  ang "Or whatever…"
  ang "I guess now at least I can be over this dumb job."
  mc "Oh… surely you won't lose your job over one little upset customer."
  "(Her death stare slides into a sidelong grimace.)"
  ang "Maybe not one customer no."
  mc "Come to think of it… They were rather accommodating after hearing your voice. Not your first offence Angela?"
  "(Her eyes snap back to glare at me)"
  ang "You don’t know me… and I don’t owe you anything. So I’m out of here. Later jerkwad."
  "(She turns to leave and I call out after her.)"
  mc "Well except the pizza."
  "(Disgusted. She realizes she’s still holding the pizza box turns and throws it at me.)"
  ang "There !@#$#! Hot and right on to ya!"
